# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" { 
  region = "us-east-2"
}

terraform {
  required_providers { 
   aws = {
     source = "hashicorp/aws"
     #version = "=2.97.0"
   }
 }

  backend "s3" {
  }

 
}
